### ISSUE TITLE
(will come home late today) FINAL: a list of what we have to do

### ISSUE THREAD

**Issue by ghost** [Aaaaaaa3/musicSchooooooooooooooooooooool#24]
hey tash i'll get home pretty late today so i can't work on it much ahh--- But if you could work on the rest today here's a list of everything we have left:

- [x] 4. make sure we display the **condition** somewhere
- [x] 1.**teacher and the student alert thing**
- [x] 2. **moving the add/edit/delete methods from Inventory into Teacher** (but keep the previous/next in Inventory as both teachers and students can view the inventory)
- [x] 3. make sure we **sort chrono** before displaying what the teacher sees
- [x] 5. **rename** the file from "Tasha.txt" to something more appropriate
- [x] 6.  **split it up** into instruments, sheet music, and equipment instead of just "items"
- [x] 7. final testing for bugs
- [ ] 8. **encapsulation**
- [ ] 9. comments + headers

NOTES:

- [x] - error checking on Edit.java -> user cannot enter a student/instrument number with letters
- [ ] - make it look more presentable
- [x] - triple check we're sorting it at the correct times (ie. after edit, adding...)

We're almost done~ Go go go go go :)

**Comment by Aaaaaaa3** [comment]
1- I just added the "overdue" label onto recentStudent and recent
2- Edit and delete works fine, but probably need to edit the add function
3- Condition as in "out to repairs" or status as in "sheet music", "instrument", etc
6- I added "status" in the class Items, and changed MusicResource, Add and Edit
7-did you update all the files though? there's still the issue with inventory(students), and sign out doesn't seem to work properly- I could probably edit signout on my own though-nvm too long I can't read/understand that, but we need to add in the status thing, remove the add option, and get rid of the number because the names are all unique anyways
8-does the gui components have to be private? otherwise I didn't find anything that was public

**Comment by Aaaaaaa3** [comment]
- [x] put "go back" buttons in studentGUI and teacherGUI

- [ ] check that all actionListener class names are capitalized 

- [x] Edit.java -> cannot change name to an already existing name(having difficulty with this one)

(optional)
- [ ] change MenuGUI.createPopUp(msg) into JOptionPane.showMessageDialog(null, msg);
cause that's a built in method
- [x] add/remove student? is that needed?

**Comment by Aaaaaaa3** [comment]
Added:
Add.java (cause signout was kinda weird- did you update it?)

I shared all my current files via google drive, cause I didn't want to screw anything up here
keep the ver. here as the master copy though

**Comment by ghost** [comment]
I kept signout's name the way it was because i couldnt figure out a good name for it
since it both signs out and adds items
